version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/docker-infra/home"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
    groups:
      beszel:
        patterns:
          - "henrygd/beszel*"
